# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200429_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
