# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200429_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='question',
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
